# Generated by Django 4.2.1 on 2023-05-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('staff_image', models.ImageField(blank=True, upload_to='staff/images')),
                ('phone_number', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('cleaner', 'Custodian'), ('junior_beauty_technician', 'Junior Beauty Technician'), ('braiding_specialist', 'Braiding Specialist'), ('senior_hair_stylist', 'Senior Hair Stylist'), ('manager', 'Manager')], max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('bantu_knots', 'Bantu Knots'), ('box_braids', 'Box Braids'), ('feed_in_braids', 'Feed-in Braids'), ('tribal_braids', 'Tribal Braids'), ('passion_twists', 'Passion Twists')], max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.service')),
            ],
        ),
    ]
