# Generated by Django 4.2.1 on 2023-06-14 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_customer_staffmember_alter_service_name_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
