# Generated by Django 4.2.1 on 2023-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_appointment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='img/chuenza.PNG', upload_to='img'),
        ),
    ]
